export const products = [
  {
    "id": "combo-caramelo-1-refri",
    "sourceProductId": 12098624,
    "name": "Combo Caramelo + 1 refri",
    "category": "AÇÃO DO DIA!",
    "description": "Pão de brioche, delicioso hambúguer de 180g, duas fatias de queijo chedar, bacon, maionese da casa e ketchup. + 1 batata M e um refrigerante lata (guaraná, coca, fanta laranja ou sprite).\n\n*Favor especificar as bebidas, caso contrário mandaremos aleatoriamente.",
    "price": 44.9,
    "priceLabel": "R$ 44,90",
    "code": "10087",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12111973/picture/large/260625192840",
    "url": "https://bbonca.com.br/detail/12098624"
  },
  {
    "id": "caramelo",
    "sourceProductId": 12719140,
    "name": "Caramelo",
    "category": "LANÇAMENTOS",
    "description": "Pão de brioche, delicioso hambúguer de 180g, duas fatias de queijo chedar, bacon, maionese da casa e ketchup.",
    "price": 32.9,
    "priceLabel": "R$ 32,90",
    "code": "10136",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12733140/picture/large/260617134215",
    "url": "https://bbonca.com.br/detail/12719140"
  },
  {
    "id": "capitu",
    "sourceProductId": 12564995,
    "name": "Capitu",
    "category": "LANÇAMENTOS",
    "description": "DE R$52,00 POR R$41,60.\nCebola crispys, molho barbecue de goiabada, catupiry, bacon, hamburguer de 180g e pão BB Onça exclusivo.",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "10119",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12578826/picture/large/260623122650",
    "url": "https://bbonca.com.br/detail/12564995"
  },
  {
    "id": "capitu-2",
    "sourceProductId": 12558061,
    "name": "Capitu",
    "category": "LANÇAMENTOS",
    "description": "Cebola crispys, molho barbecue de goiabada, catupiry, bacon, hamburguer de 180g e pão BB Onça exclusivo.",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "10119",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12571880/picture/large/260617133248",
    "url": "https://bbonca.com.br/detail/12558061"
  },
  {
    "id": "combo-do-rei",
    "sourceProductId": 4622175,
    "name": "Combo do REI",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "2 Burguers Mufasa (Pão de brioche, delicioso hambúrguer de 180g assado na brasa, CATUPIRY LEGÍTIMO EMPANADO, geléia de pimenta, bacon crocante, rúcula, ketchup, maionese verde caseira) + \n2 batatas M + \n2 refrigerantes lata (guaraná, coca, fanta laranja ou sprite), favor especificar as bebidas, caso contrario mandaremos aleatória. \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\nEspecificar o ponto da carne",
    "price": 128,
    "priceLabel": "R$ 128,00",
    "code": "68",
    "image": "https://www.goomer.app/webmenu/bbonca/product/4625156/picture/large/260615200710",
    "url": "https://bbonca.com.br/detail/4622175"
  },
  {
    "id": "seu-mufasa-o-rei",
    "sourceProductId": 12430078,
    "name": "Seu Mufasa - O Rei",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "DE R$52,00 POR R$41,60\n\nCATUPIRY LEGÍTIMO EMPANADO, geleia de pimenta, bacon, rúcula, ketchup, maionese verde caseira  pão de brioche, delicioso hambúrguer de 180g assado na brasa. \n(Não cortamos ao meio, pois corre risco do catupiry empanado estourar e perder muito recheio).\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "1",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443784/picture/large/260623122705",
    "url": "https://bbonca.com.br/detail/12430078"
  },
  {
    "id": "seu-mufasa-o-rei-2",
    "sourceProductId": 2585315,
    "name": "Seu Mufasa - O Rei",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "CATUPIRY LEGÍTIMO EMPANADO, geleia de pimenta, bacon, rúcula, ketchup, maionese verde caseira  pão de brioche, delicioso hambúrguer de 180g assado na brasa. \n(Não cortamos ao meio, pois corre risco do catupiry empanado estourar e perder muito recheio).\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nfoto ilustrativa",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "1",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2586024/picture/large/260612223006",
    "url": "https://bbonca.com.br/detail/2585315"
  },
  {
    "id": "dona-ursula-4-queijos",
    "sourceProductId": 2219345,
    "name": "Dona Úrsula  - 4 Queijos",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "Molho de 4 queijos cremoso, bacon, rúcula, maionese verde caseira, pão de brioche, delicioso hambúrguer de 180g assado na brasa,e ketchup. \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(O burguer não acompanha batata).\nfoto ilustrativa",
    "price": 47,
    "priceLabel": "R$ 47,00",
    "code": "3",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2219585/picture/large/260612223416",
    "url": "https://bbonca.com.br/detail/2219345"
  },
  {
    "id": "dona-ursula-4-queijos-2",
    "sourceProductId": 12430079,
    "name": "Dona Úrsula  - 4 Queijos",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "DE R$47,00 POR R$37,60\n\nMolho de 4 queijos cremoso, bacon, rúcula, maionese verde caseira, pão de brioche, delicioso hambúrguer de 180g assado na brasa,e ketchup. \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(O burguer não acompanha batata).\nfoto ilustrativa",
    "price": 37.6,
    "priceLabel": "R$ 37,60",
    "code": "3",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443785/picture/large/260623122711",
    "url": "https://bbonca.com.br/detail/12430079"
  },
  {
    "id": "dona-onca-o-x-tudo-da-toca",
    "sourceProductId": 2219387,
    "name": "Dona Onça  - O X Tudo da toca",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "2 deliciosos hambúrgueres de 120g assado na brasa, queijo cheddar fatiado, molho 4 queijos,  bacon, ovo, cebola caramelizada, rúcula, alface americana, tomate, maionese da casa e ketchup. \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "6",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2219627/picture/large/260612223434",
    "url": "https://bbonca.com.br/detail/2219387"
  },
  {
    "id": "dona-onca-o-x-tudo-da-toca-2",
    "sourceProductId": 12430081,
    "name": "Dona Onça  - O X Tudo da toca",
    "category": "OS MAIS VENDIDOS DA TOCA",
    "description": "DE R$52,00 POR R$41,60\n\n2 deliciosos hambúrgueres de 120g assado na brasa, queijo cheddar fatiado, molho 4 queijos,  bacon, ovo, cebola caramelizada, rúcula, alface americana, tomate, maionese da casa e ketchup. \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "6",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443787/picture/large/260623122717",
    "url": "https://bbonca.com.br/detail/12430081"
  },
  {
    "id": "seu-mufasa",
    "sourceProductId": 12430191,
    "name": "Seu Mufasa",
    "category": "ESPECIAIS",
    "description": "DE R$52,00 POR R$41,60\nSOMENTE COM CATUPIRY\nCATUPIRY LEGÍTIMO EMPANADO, geleia de pimenta, bacon, rúcula, ketchup, maionese verde caseira, pão de brioche, delicioso hambúrguer de 180g assado na brasa.\n(Não cortamos ao meio, pois corre risco do catupiry empanado estourar e perder muito recheio).\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "1",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443897/picture/large/260623122748",
    "url": "https://bbonca.com.br/detail/12430191"
  },
  {
    "id": "mufasa-2-mucarela",
    "sourceProductId": 12430195,
    "name": "Mufasa 2 (muçarela)",
    "category": "ESPECIAIS",
    "description": "DE R$52,00 POR R$41,60\nMUÇARELA EMPANADA, geleia de pimenta, bacon, rúcula, ketchup, maionese verde caseira, pão de brioche, delicioso hambúrguer de 180g assado na brasa.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(Não cortamos ao meio)\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "1312",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443901/picture/large/260623122755",
    "url": "https://bbonca.com.br/detail/12430195"
  },
  {
    "id": "mufasa-2-mucarela-2",
    "sourceProductId": 9519498,
    "name": "Mufasa 2 (muçarela)",
    "category": "ESPECIAIS",
    "description": "MUÇARELA EMPANADA, geleia de pimenta, bacon, rúcula, ketchup, maionese verde caseira, pão de brioche, delicioso hambúrguer de 180g assado na brasa.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(Não cortamos ao meio)\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nfoto ilustrativa",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "1312",
    "image": "https://www.goomer.app/webmenu/bbonca/product/9529452/picture/large/260612223459",
    "url": "https://bbonca.com.br/detail/9519498"
  },
  {
    "id": "dona-onca-o-x-tudo-da-toca-3",
    "sourceProductId": 11933334,
    "name": "Dona Onça  - O X Tudo da toca",
    "category": "ESPECIAIS",
    "description": "2 deliciosos hambúrgueres de 120g assado na brasa, queijo cheddar fatiado, molho 4 queijos, bacon, ovo, cebola caramelizada, pão de brioche, rúcula, alface americana, tomate, maionese da casa e ketchup. \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "6",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11946511/picture/large/260613162547",
    "url": "https://bbonca.com.br/detail/11933334"
  },
  {
    "id": "dona-onca-o-x-tudo-da-toca-4",
    "sourceProductId": 12430196,
    "name": "Dona Onça  - O X Tudo da toca",
    "category": "ESPECIAIS",
    "description": "DE R$52,00 POR R$41,60\n\n2 deliciosos hambúrgueres de 120g assado na brasa, queijo cheddar fatiado, molho 4 queijos, bacon, ovo, cebola caramelizada, pão de brioche, rúcula, alface americana, tomate, maionese da casa e ketchup. PONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "6",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443902/picture/large/260623122759",
    "url": "https://bbonca.com.br/detail/12430196"
  },
  {
    "id": "tio-brito",
    "sourceProductId": 12430199,
    "name": "Tio Brito",
    "category": "ESPECIAIS",
    "description": "DE R$47,00 POR R$37,60\nCreme de cheddar cremoso, cebola caramelizada, bacon, maionese caseira e ketchup, pão de brioche, delicioso hambúrguer de 180g assado na brasa. \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 37.6,
    "priceLabel": "R$ 37,60",
    "code": "4",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443905/picture/large/260623122804",
    "url": "https://bbonca.com.br/detail/12430199"
  },
  {
    "id": "tio-brito-2",
    "sourceProductId": 2219320,
    "name": "Tio Brito",
    "category": "ESPECIAIS",
    "description": "Creme de cheddar cremoso, cebola caramelizada, bacon, maionese caseira e ketchup, pão de brioche, delicioso hambúrguer de 180g assado na brasa.\nPONTOS DA CARNE:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 47,
    "priceLabel": "R$ 47,00",
    "code": "4",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2219560/picture/large/260612223953",
    "url": "https://bbonca.com.br/detail/2219320"
  },
  {
    "id": "ferdinando",
    "sourceProductId": 12430201,
    "name": "Ferdinando",
    "category": "ESPECIAIS",
    "description": "DE R$52,00 POR R$41,60\n\nCostela desfiada com queijo, maionese de chimichurri, carne 180g, cebola roxa, ketchup e pão BB Onça,.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 41.6,
    "priceLabel": "R$ 41,60",
    "code": "1341",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443907/picture/large/260623122808",
    "url": "https://bbonca.com.br/detail/12430201"
  },
  {
    "id": "ferdinando-2",
    "sourceProductId": 10070395,
    "name": "Ferdinando",
    "category": "ESPECIAIS",
    "description": "Costela desfiada com queijo, maionese de chimichurri, carne 180g, cebola roxa, ketchup e pão BB Onça.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 52,
    "priceLabel": "R$ 52,00",
    "code": "1341",
    "image": "https://www.goomer.app/webmenu/bbonca/product/10081366/picture/large/260612224004",
    "url": "https://bbonca.com.br/detail/10070395"
  },
  {
    "id": "mr-panda",
    "sourceProductId": 2219377,
    "name": "Mr. Panda",
    "category": "ESPECIAIS",
    "description": "Shimeji com cream cheese derretido na chapa, tarê ,pão de brioche, delicioso hambúrguer de 180g assado na brasa, maionese caseira e ketchup.  \nOpção de adicionar fritas nos combos.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 47,
    "priceLabel": "R$ 47,00",
    "code": "5",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2219617/picture/large/260612224019",
    "url": "https://bbonca.com.br/detail/2219377"
  },
  {
    "id": "jack-ze",
    "sourceProductId": 12430204,
    "name": "Jack Zé",
    "category": "ESPECIAIS",
    "description": "DE R$47,00 POR R$37,60\n\nCATUPIRY LEGÍTIMO, alho torradinho, bacon, pão de brioche, delicioso hambúrguer de 180g assado na brasa, maionese caseira e ketchup. \nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 37.6,
    "priceLabel": "R$ 37,60",
    "code": "2",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443910/picture/large/260623122822",
    "url": "https://bbonca.com.br/detail/12430204"
  },
  {
    "id": "jack-ze-2",
    "sourceProductId": 2219337,
    "name": "Jack Zé",
    "category": "ESPECIAIS",
    "description": "CATUPIRY LEGÍTIMO, alho torradinho, bacon, pão de brioche, delicioso hambúrguer de 180g assado na brasa, maionese caseira e ketchup. \nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca . \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 47,
    "priceLabel": "R$ 47,00",
    "code": "2",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2219577/picture/large/260612224029",
    "url": "https://bbonca.com.br/detail/2219337"
  },
  {
    "id": "bb-tradicional-o-x-burguer-da-toca",
    "sourceProductId": 12430085,
    "name": "BB Tradicional - O X Burguer da toca",
    "category": "TRADICIONAIS",
    "description": "DE R$38,00 POR R$30,40\n\nPão de brioche, delicioso hambúrguer de 180g assado na brasa, queijo muçarela derretido, maionese caseira e ketchup. \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 30.4,
    "priceLabel": "R$ 30,40",
    "code": "7",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443791/picture/large/260623122839",
    "url": "https://bbonca.com.br/detail/12430085"
  },
  {
    "id": "bb-tradicional-o-x-burguer-da-toca-2",
    "sourceProductId": 3199785,
    "name": "BB Tradicional - O X Burguer da toca",
    "category": "TRADICIONAIS",
    "description": "Pão de brioche, delicioso hambúrguer de 180g assado na brasa, queijo muçarela derretido, maionese caseira e ketchup. \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 38,
    "priceLabel": "R$ 38,00",
    "code": "7",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201252/picture/large/260612224112",
    "url": "https://bbonca.com.br/detail/3199785"
  },
  {
    "id": "bb-salada-o-x-salada-da-toca",
    "sourceProductId": 12430086,
    "name": "BB Salada - O X Salada da toca",
    "category": "TRADICIONAIS",
    "description": "DE R$40,00 POR R$32,00\n\nPão de brioche, delicioso hambúrguer de 180g assado na brasa, queijo muçarela derretida, maionese caseira, alface, tomate, cebola roxa e ketchup.  \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 32,
    "priceLabel": "R$ 32,00",
    "code": "9",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443792/picture/large/260623122845",
    "url": "https://bbonca.com.br/detail/12430086"
  },
  {
    "id": "bb-salada-o-x-salada-da-toca-2",
    "sourceProductId": 11933258,
    "name": "BB Salada - O X Salada da toca",
    "category": "TRADICIONAIS",
    "description": "Pão de brioche, delicioso hambúrguer de 180g assado na brasa, queijo muçarela derretida, maionese caseira, alface, tomate, cebola roxa e ketchup.  \n\nPONTOS DAS CARNES:\nMAL PASSADA: selada por fora e de cor viva, avermelhada.\nCARNE AO PONTO: é rosada por dentro.\nBEM PASSADO: sem suculência e seca .\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 40,
    "priceLabel": "R$ 40,00",
    "code": "9",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11946436/picture/large/260612224120",
    "url": "https://bbonca.com.br/detail/11933258"
  },
  {
    "id": "bb-onca-kids",
    "sourceProductId": 3199806,
    "name": "BB Onça Kids",
    "category": "TRADICIONAIS",
    "description": "Pão kids, hambúrguer de 120g e queijo cheddar fatiado.  (O burguer não acompanha batata)\n\nFoto ilustrativa.\n(O burguer não acompanha batata)\n\nPONTO BEM PASSADO: sem suculência e seca .",
    "price": 28,
    "priceLabel": "R$ 28,00",
    "code": "8",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201273/picture/large/260612224130",
    "url": "https://bbonca.com.br/detail/3199806"
  },
  {
    "id": "bb-onca-kids-2",
    "sourceProductId": 12430102,
    "name": "BB Onça Kids",
    "category": "TRADICIONAIS",
    "description": "DE R$28,00 POR R$22,40\nPão kids, hambúrguer de 120g e queijo cheddar fatiado.  (O burguer não acompanha batata)\n\nFoto ilustrativa.\n(O burguer não acompanha batata)\n\nPONTO BEM PASSADO: sem suculência e seca .",
    "price": 22.4,
    "priceLabel": "R$ 22,40",
    "code": "8",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443808/picture/large/260623122850",
    "url": "https://bbonca.com.br/detail/12430102"
  },
  {
    "id": "alvin-vegetariano",
    "sourceProductId": 12430104,
    "name": "Alvin (vegetariano)",
    "category": "TRADICIONAIS",
    "description": "DE R$36,00 POR R$28,80\n\nCreme de shimeji, geleia de pimenta, delicioso hambúrguer de catupiry, pão de brioche, ketchup, maionese verde, rúcula. \n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nfoto ilustrativa",
    "price": 28.8,
    "priceLabel": "R$ 28,80",
    "code": "64",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443810/picture/large/260713234627",
    "url": "https://bbonca.com.br/detail/12430104"
  },
  {
    "id": "alvin-vegetariano-2",
    "sourceProductId": 4297040,
    "name": "Alvin (vegetariano)",
    "category": "TRADICIONAIS",
    "description": "Creme de shimeji, geleia de pimenta, delicioso hambúrguer de catupiry, pão de brioche, ketchup, maionese verde, rúcula.\n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nfoto ilustrativa",
    "price": 36,
    "priceLabel": "R$ 36,00",
    "code": "64",
    "image": "https://www.goomer.app/webmenu/bbonca/product/4299662/picture/large/260612224140",
    "url": "https://bbonca.com.br/detail/4297040"
  },
  {
    "id": "alvin-2-vegetariano",
    "sourceProductId": 12382263,
    "name": "Alvin 2 (vegetariano)",
    "category": "TRADICIONAIS",
    "description": "Creme de shimeji, geleia de pimenta, delicioso hambúrguer de muçarela, pão de brioche, ketchup, maionese verde, rúcula. \n(O burguer não acompanha batata).\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n\nfoto ilustrativa",
    "price": 36,
    "priceLabel": "R$ 36,00",
    "code": "10083",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12395903/picture/large/260612224151",
    "url": "https://bbonca.com.br/detail/12382263"
  },
  {
    "id": "frangolino-tradicional-grelhado",
    "sourceProductId": 11933328,
    "name": "Frangolino Tradicional Grelhado",
    "category": "BURGUER DE FRANGO",
    "description": "Delicioso hambúrguer de frango 120g assado na brasa, queijo cheddar fatiado, cebola roxa, alface americana, tomate, ketchup, dupla dose de maionese da casa e pão de brioche,\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 32,
    "priceLabel": "R$ 32,00",
    "code": "59",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11946506/picture/large/260612224224",
    "url": "https://bbonca.com.br/detail/11933328"
  },
  {
    "id": "frangolino-tradicional-grelhado-2",
    "sourceProductId": 12430209,
    "name": "Frangolino Tradicional Grelhado",
    "category": "BURGUER DE FRANGO",
    "description": "DE R$32,00 POR R$25,60\n\nDelicioso hambúrguer de frango 120g assado na brasa, queijo cheddar fatiado, cebola roxa, alface americana, tomate, ketchup, dupla dose de maionese da casa e pão de brioche, \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 25.6,
    "priceLabel": "R$ 25,60",
    "code": "59",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443915/picture/large/260623122910",
    "url": "https://bbonca.com.br/detail/12430209"
  },
  {
    "id": "frangolino-especial-empanado",
    "sourceProductId": 12430210,
    "name": "Frangolino Especial Empanado",
    "category": "BURGUER DE FRANGO",
    "description": "DE R$37,00 POR R$29,60\n\nMolho especial cream cheese, delicioso hambúrguer de frango 120g empanado, queijo cheddar fatiado, alface americana, tomate, ketchup, maionese da casa. e pão de brioche.\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 29.6,
    "priceLabel": "R$ 29,60",
    "code": "60",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443916/picture/large/260623122914",
    "url": "https://bbonca.com.br/detail/12430210"
  },
  {
    "id": "frangolino-especial-empanado-2",
    "sourceProductId": 11933337,
    "name": "Frangolino Especial Empanado",
    "category": "BURGUER DE FRANGO",
    "description": "Molho especial cream cheese, delicioso hambúrguer de frango 120g empanado, queijo cheddar fatiado, alface americana, tomate, ketchup, maionese da casa. e pão de brioche.\n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 37,
    "priceLabel": "R$ 37,00",
    "code": "60",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11946515/picture/large/260612224231",
    "url": "https://bbonca.com.br/detail/11933337"
  },
  {
    "id": "smash-martin",
    "sourceProductId": 12430214,
    "name": "Smash Martin",
    "category": "SMASH",
    "description": "1.0: DE R$41,00 POR $32,80\n2.0: DE R$46,00 POR $36,80\n\n1 ou 2 hambúrgueres smash, creme de cheddar, creme de queijos, bacon, cebola roxa, alface americana, tomate, maionese da casa, ketchup e pão de brioche.  \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 32.8,
    "priceLabel": "R$ 32,80",
    "code": "10",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443920/picture/large/260623122924",
    "url": "https://bbonca.com.br/detail/12430214"
  },
  {
    "id": "smash-martin-2",
    "sourceProductId": 12430214,
    "name": "Smash Martin",
    "category": "SMASH",
    "description": "1.0: DE R$41,00 POR $32,80\n2.0: DE R$46,00 POR $36,80\n\n1 ou 2 hambúrgueres smash, creme de cheddar, creme de queijos, bacon, cebola roxa, alface americana, tomate, maionese da casa, ketchup e pão de brioche.  \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 36.8,
    "priceLabel": "R$ 36,80",
    "code": "34",
    "image": "https://www.goomer.app/webmenu/bbonca/product/12443920/picture/large/260623122924",
    "url": "https://bbonca.com.br/detail/12430214"
  },
  {
    "id": "smash-martin-3",
    "sourceProductId": 3200099,
    "name": "Smash Martin",
    "category": "SMASH",
    "description": "1 ou 2 hambúrgueres smash, creme de cheddar, creme de queijos, bacon, cebola roxa, alface americana, tomate, maionese da casa, ketchup e pão de brioche.  \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 41,
    "priceLabel": "R$ 41,00",
    "code": "10",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201566/picture/large/260613162902",
    "url": "https://bbonca.com.br/detail/3200099"
  },
  {
    "id": "smash-martin-4",
    "sourceProductId": 3200099,
    "name": "Smash Martin",
    "category": "SMASH",
    "description": "1 ou 2 hambúrgueres smash, creme de cheddar, creme de queijos, bacon, cebola roxa, alface americana, tomate, maionese da casa, ketchup e pão de brioche.  \n\nOBS: Não trocamos nenhum ingrediente do burguer e não mandamos a parte.\n(O burguer não acompanha batata).\n\nfoto ilustrativa",
    "price": 46,
    "priceLabel": "R$ 46,00",
    "code": "34",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201566/picture/large/260613162902",
    "url": "https://bbonca.com.br/detail/3200099"
  },
  {
    "id": "batata-tradicional",
    "sourceProductId": 3200265,
    "name": "Batata tradicional",
    "category": "PORÇÕES",
    "description": "Batatas fritas acompanhadas da famosa maionese da casa.\nOBS: BATATA TAMANHO G, INDIVIDUAL.",
    "price": 18,
    "priceLabel": "R$ 18,00",
    "code": "1266",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201732/picture/large/260612224640",
    "url": "https://bbonca.com.br/detail/3200265"
  },
  {
    "id": "batata-bb-onca",
    "sourceProductId": 11886030,
    "name": "Batata BB Onça",
    "category": "PORÇÕES",
    "description": "Batata com creme de cheddar, creme de queijo e bacon.",
    "price": 34,
    "priceLabel": "R$ 34,00",
    "code": "10063",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11899157/picture/large/260616202809",
    "url": "https://bbonca.com.br/detail/11886030"
  },
  {
    "id": "mickey-mussa",
    "sourceProductId": 10378576,
    "name": "Mickey Mussa",
    "category": "PORÇÕES",
    "description": "Porção com 8 unidades de mussarela empanada.\nAcompanha geleia de pimenta e fio de mel.\n\n*A Mussarela pode ter alteração de textura e aparência devido ao trajeto da entrega*",
    "price": 34,
    "priceLabel": "R$ 34,00",
    "code": "10064",
    "image": "https://www.goomer.app/webmenu/bbonca/product/10389921/picture/large/260618230510",
    "url": "https://bbonca.com.br/detail/10378576"
  },
  {
    "id": "maristelas",
    "sourceProductId": 11099657,
    "name": "Maristelas",
    "category": "PORÇÕES",
    "description": "Bolinho de Costela com Catupiry cremoso!\n7 unidades. \nAcompanha maionese de chimichurri especial!",
    "price": 34,
    "priceLabel": "R$ 34,00",
    "code": "10065",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11111867/picture/large/260612224742",
    "url": "https://bbonca.com.br/detail/11099657"
  },
  {
    "id": "batata-bb-onca-2",
    "sourceProductId": 11933342,
    "name": "Batata BB Onça",
    "category": "PORÇÕES",
    "description": "Batata com cheddar, creme de queijo e bacon.\nOBS: BATATA TAMANHO G, INDIVIDUAL",
    "price": 34,
    "priceLabel": "R$ 34,00",
    "code": "10063",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11946520/picture/large/260616212501",
    "url": "https://bbonca.com.br/detail/11933342"
  },
  {
    "id": "coca-cola-zero",
    "sourceProductId": 2240776,
    "name": "Coca-Cola ZERO",
    "category": "BEBIDAS",
    "description": "Lata 350ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "13",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2241026/picture/large/260613000855",
    "url": "https://bbonca.com.br/detail/2240776"
  },
  {
    "id": "coca-cola",
    "sourceProductId": 2211606,
    "name": "Coca-Cola",
    "category": "BEBIDAS",
    "description": "Lata 350ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "12",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2211840/picture/large/260613000902",
    "url": "https://bbonca.com.br/detail/2211606"
  },
  {
    "id": "guarana",
    "sourceProductId": 2211607,
    "name": "Guaraná",
    "category": "BEBIDAS",
    "description": "Lata 350ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "14",
    "image": "https://www.goomer.app/webmenu/bbonca/product/2211841/picture/large/260613000951",
    "url": "https://bbonca.com.br/detail/2211607"
  },
  {
    "id": "fanta-laranja",
    "sourceProductId": 4997353,
    "name": "Fanta Laranja",
    "category": "BEBIDAS",
    "description": "350 ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "70",
    "image": "https://www.goomer.app/webmenu/bbonca/product/5000755/picture/large/260704212928",
    "url": "https://bbonca.com.br/detail/4997353"
  },
  {
    "id": "sprite",
    "sourceProductId": 4177413,
    "name": "Sprite",
    "category": "BEBIDAS",
    "description": "Lata 350 ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "57",
    "image": "https://www.goomer.app/webmenu/bbonca/product/4179911/picture/large/260613001021",
    "url": "https://bbonca.com.br/detail/4177413"
  },
  {
    "id": "coca-cola-zero-2l",
    "sourceProductId": 11772221,
    "name": "Coca-Cola Zero 2L",
    "category": "BEBIDAS",
    "description": "",
    "price": 17,
    "priceLabel": "R$ 17,00",
    "code": "1301",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11785224/picture/large/260621224840",
    "url": "https://bbonca.com.br/detail/11772221"
  },
  {
    "id": "coca-cola-2l",
    "sourceProductId": 4304729,
    "name": "Coca Cola 2L",
    "category": "BEBIDAS",
    "description": "2L",
    "price": 17,
    "priceLabel": "R$ 17,00",
    "code": "44",
    "image": "https://www.goomer.app/webmenu/bbonca/product/4307368/picture/large/260624192758",
    "url": "https://bbonca.com.br/detail/4304729"
  },
  {
    "id": "agua",
    "sourceProductId": 3199763,
    "name": "Água",
    "category": "BEBIDAS",
    "description": "Garrafa 500ml",
    "price": 5,
    "priceLabel": "R$ 5,00",
    "code": "42",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201230/picture/large/260613002100",
    "url": "https://bbonca.com.br/detail/3199763"
  },
  {
    "id": "heineken-long-neck",
    "sourceProductId": 3199692,
    "name": "Heineken Long Neck",
    "category": "BEBIDAS",
    "description": "Garrafa 330ml",
    "price": 15,
    "priceLabel": "R$ 15,00",
    "code": "17",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201159/picture/large/260527000000",
    "url": "https://bbonca.com.br/detail/3199692"
  },
  {
    "id": "budweiser-long-neck",
    "sourceProductId": 3199733,
    "name": "Budweiser Long Neck",
    "category": "BEBIDAS",
    "description": "Garrafa 330ml",
    "price": 12,
    "priceLabel": "R$ 12,00",
    "code": "18",
    "image": "https://www.goomer.app/webmenu/bbonca/product/3201200/picture/large/260608200840",
    "url": "https://bbonca.com.br/detail/3199733"
  },
  {
    "id": "h2o",
    "sourceProductId": 9997648,
    "name": "H2O",
    "category": "BEBIDAS",
    "description": "h2o refrigerante limão 500 ml",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "45",
    "image": "https://www.goomer.app/webmenu/bbonca/product/10008470/picture/large/260613002225",
    "url": "https://bbonca.com.br/detail/9997648"
  },
  {
    "id": "limoneto",
    "sourceProductId": 11528080,
    "name": "Limoneto",
    "category": "BEBIDAS",
    "description": "Limoneto 500ml.",
    "price": 9,
    "priceLabel": "R$ 9,00",
    "code": "87",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11540809/picture/large/260613002233",
    "url": "https://bbonca.com.br/detail/11528080"
  },
  {
    "id": "agua-mineral-com-gas-500ml",
    "sourceProductId": 11772220,
    "name": "Água Mineral Com Gás 500ml",
    "category": "BEBIDAS",
    "description": "",
    "price": 5.5,
    "priceLabel": "R$ 5,50",
    "code": "47",
    "image": "https://www.goomer.app/webmenu/bbonca/product/11785223/picture/large/260613002110",
    "url": "https://bbonca.com.br/detail/11772220"
  },
  {
    "id": "suco-del-valle-maracuja",
    "sourceProductId": 10326589,
    "name": "Suco Del Valle Maracuja",
    "category": "BEBIDAS",
    "description": "Suco Del Valle Maracuja 290ml",
    "price": 7,
    "priceLabel": "R$ 7,00",
    "code": "74",
    "image": "https://www.goomer.app/webmenu/bbonca/product/10337882/picture/large/260613002310",
    "url": "https://bbonca.com.br/detail/10326589"
  }
];
